### ISSUE TITLE
Ambix LV2 plugins and standalones seem to crash on ArchLinux

### ISSUE THREAD

**Issue by jcelerier** [kronihias/ambix#34]
Example: 

```
Thread 1 "ambix_binaural" received signal SIGSEGV, Segmentation fault.
0x0000555555919470 in ?? ()
(gdb) bt
#0  0x0000555555919470 in ?? ()
#1  0x000055555593520b in ?? ()
#2  0x000055555591808b in ?? ()
#3  0x000055555589aa83 in juce::Graphics::fillAll(juce::Colour) const ()
#4  0x0000555555a41681 in juce::ResizableWindow::paint(juce::Graphics&) ()
#5  0x0000555555a3a5cf in juce::DocumentWindow::paint(juce::Graphics&) ()
#6  0x000055555596cabf in juce::Component::paintComponentAndChildren(juce::Graphics&) ()
#7  0x0000555555a3eee7 in juce::ComponentPeer::handlePaint(juce::LowLevelGraphicsContext&) ()
#8  0x0000555555a584e2 in ?? ()
#9  0x000055555587e677 in ?? ()
#10 0x000055555587aed4 in juce::MessageManager::runDispatchLoop() ()
#11 0x00005555556cc373 in juce::JUCEApplicationBase::main() ()
#12 0x00007ffff7229290 in __libc_start_call_main (main=main@entry=0x5555556cc2e0 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdca8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#13 0x00007ffff722934a in __libc_start_main_impl (main=0x5555556cc2e0 <main>, argc=1, argv=0x7fffffffdca8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdc98) at ../csu/libc-start.c:389
#14 0x00005555556ce3ee in _start ()
```

**Comment by escuta** [comment]
I can second this!

**Comment by dvzrv** [comment]
I have just pushed 0.3.0 to testing, in case you want to give those plugins another try (they were loadable at least in carla).

**Comment by jcelerier** [comment]
thanks, trying !

**Comment by jcelerier** [comment]
<img width="1891" height="1421" alt="Image" src="https://github.com/user-attachments/assets/17b9366e-0d83-409a-859f-c949b0f69d59" />

crash is gone!
however ambix-encoder seems to have a problem with its display - the top area widget seems to show only what is below when the vst widget opens.

It also happens when i switch between virtual desktops

<img width="382" height="434" alt="Image" src="https://github.com/user-attachments/assets/5e4880d1-381c-4a3f-8d07-5829accd7a25" />

(as unlikely as it seems i actually had @escuta's website open right here aha)

**Comment by kronihias** [comment]
many linux affecting changes have been added recently, you may want to test again with the latest version
